# Generated by Django 6.0.3 on 2026-03-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.FloatField()),
                ('quiz_score', models.FloatField()),
                ('study_hours', models.FloatField()),
                ('performance_score', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
